"""add-users-password

Revision ID: 507061b0f5f0
Revises: 0001_create_users
Create Date: 2026-09-18 16:32:21.804193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '507061b0f5f0'
down_revision: Union[str, None] = '0001_create_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Unicode(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
